import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = {
    userName: "Roman",
     password: "123456"
   }
 
  return (
    <html lang="en">
      <body className={` antialiased`}>
      {
        user && (
          <div className="grid min-h-screen grid-cols-[200px_1fr] grid-rows-[auto_1fr_auto] gap-4">
            <Header />
            <Sidebar />
              <main className="gap-4 border-2 border-secondary">
                {children}
              </main>
            <Footer />
          </div>
        )
      }
      


    </body>
    </html>
  );
}
